services:
  - type: web
    name: emotic-based-music-recommendation
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
